spring.application.name=app

server.port=8080

spring.profiles.include=dev,test,private,cloud,secret

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/sloway
spring.datasource.username=postgres
spring.datasource.password=postgreskh

#JPA
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#spring.jpa.hibernate.ddl-auto=update

spring.jpa.hibernate.ddl-auto=create

# spring.jpa.hibernate.ddl-auto=create-drop

# spring.jpa.hibernate.ddl-auto=validate

app.base-url=http://localhost:8080
app.frontend-url=http://localhost:5173
