cloud.aws.s3.bucket=sloway-fileserver
cloud.aws.region=ap-northeast-2


cloud.aws.credentials.access-key=AKIAY3ZEVCH7QXWEP5CF
cloud.aws.credentials.secret-key=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

